apiVersion: v1
kind: Service
metadata:
  name: simpleService-lb
  namespace: nl2service
spec:
  type: LoadBalancer
  selector:
    app: simpleService
  ports:
    - name: http
      port: 80
      targetPort: 8080