apiVersion: v1
kind: Service
metadata:
  name: simple-service-lb
  namespace: nl2service
spec:
  type: LoadBalancer
  selector:
    app: simple-service
  ports:
    - name: http
      port: 80
      targetPort: 8080